services:
  # Nginx Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - /var/www/certbot:/var/www/certbot:ro
      - ./certs:/etc/certs:ro
      - /docker-services:/var/www/html:ro
    networks:
      - nginx
    restart: always

networks:
  nginx:
    external: true
    name: nginx
