# Usuário que executa o serviço
user nginx;

# Número de workers (auto ajusta conforme o número de núcleos de CPU)
worker_processes auto;

# Localização dos logs de erro
error_log /var/log/nginx/error.log warn;
pid /run/nginx.pid;

events {
    # Máximo de conexões simultâneas por worker
    worker_connections 1024;
    # Utiliza um método eficiente de processamento de eventos
    use epoll;
    multi_accept on;
}

http {
    # Inclui tipos de arquivos MIME
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Otimizações de rede
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    server_tokens off; # Esconde a versão do Nginx por segurança

    # Configuração de Logs
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    # Compressão Gzip (melhora a velocidade de carregamento)
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/json;

    # Inclusão de configurações externas
    # Path dos arquivos de servidor 
    include /etc/nginx/conf.d/*.conf;
}