server {
    listen 80;
    # Subtitua pelo domínio do seu site (ex: example.com)
    server_name <dns-do-seu-site>;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {

        # variável para resolver o nome do container do serviço dentro da rede do Docker
        set $upstream_aplication <nome-container>;

        # inserir nome e porta do container que o serviço roda
        proxy_pass http://$upstream_aplication:<porta>/; 

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    # Subtitua pelo domínio do seu site (ex: example.com)
    server_name <dns-do-seu-site>;

    # Resolver para resolver nomes de containers dentro da rede do Docker 
    resolver 127.0.0.11 valid=30s;

    # Caminhos do certificado SSL dentro do container nginx
    ssl_certificate /etc/certs/jimibrasil.com.br/cert.pem;
    ssl_certificate_key /etc/certs/jimibrasil.com.br/cert.key; 

    client_max_body_size 200m;
    charset utf-8;

    location / {
        # inserir nome do container que o serviço roda
        set $upstream_aplication <nome-container>;

        # inserir nome e porta do container que o serviço roda
        proxy_pass http://$upstream_aplication:<porta>/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ /.ht {
        deny all;
    }
} 